name: Publish NPM

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: pnpm install, build, build-ts, and test
              run: |
                  pnpm install
                  pnpm run build --if-present
                  # pnpm test
            - name: publish
              continue-on-error: true
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
              run: pnpm publish --no-git-checks
